version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: eco123
      POSTGRES_DB: eco
    volumes:
      - db_data:/data

volumes:
  db_data:
